package MusicUtil;

public enum NoteType {
	WHOLE_NOTE, 
	HALF_NOTE, 
	QUARTER_NOTE, 
	EIGHTH_NOTE, 
	SIXTEENTH_NOTE, 
	THIRTYSECOND_NOTE, 
	DOTTED_EIGHTH_NOTE,
	DOTTED_QUARTER_NOTE,
	DOTTED_HALF_NOTE,
	WHOLE_REST, 
	HALF_REST, 
	QUARTER_REST, 
	EIGTH_REST, 
	SIXTEENTH_REST,
	THIRTYSECOND_REST, 
	NOTANOTE; 
}
